<?xml version="1.0"?>
<!DOCTYPE SmartRestaurant [
	<!ELEMENT SmartRestaurant ( type, language, data ) >
	<!ELEMENT data ( item+ ) >
	<!ELEMENT item ( #PCDATA ) >
	<!ATTLIST item name NMTOKEN #REQUIRED >
	<!ELEMENT language ( #PCDATA ) >
	<!ELEMENT type ( #PCDATA ) >
]>
<SmartRestaurant>
	<type>translation</type>
	<language>en</language>
	<data>
		<item name="ACCESS_DENIED">access denied</item>
		<item name="ACCESS_DENIED_EXPLAIN">you have not the authorization required to enter this area.&amp;lt;br/&amp;gt;
Maybe you didn\&amp;#039;t authenticate yet or you authenticated without a password. In such cases, connect before trying to enter this zone, otherwise ask the administrator to give you the access.</item>
		<item name="ACCOUNT">Account</item>
		<item name="ACCOUNTING">Accounting</item>
		<item name="ACCOUNTING_DATABASE">Accounting Database</item>
		<item name="ACCOUNTING_DATABASES">Accounting Databases</item>
		<item name="ADD">add</item>
		<item name="ADDRESS">Address</item>
		<item name="ALL">All</item>
		<item name="ALL_TABLES">all the tables</item>
		<item name="ALREADY_CONNECTED">you are already connected</item>
		<item name="AMOUNT">Amount</item>
		<item name="ANNULL">annull record</item>
		<item name="ANNULLED">annulled</item>
		<item name="ANNULLED_ABBR">ANN</item>
		<item name="APPLY">Apply</item>
		<item name="APPLY_DISCOUNT">Apply discount</item>
		<item name="ASK_DELETE_CONFIRMATION">Do you really want to delete the order?</item>
		<item name="ASSOCIATED_INVOICE">associated invoice</item>
		<item name="ASSOCIATE_ASK">Do you want to associate this table to your ID?</item>
		<item name="ASSOCIATION">association</item>
		<item name="AUTOCALC">autocalc</item>
		<item name="AUTOCALC_LEVELS">autocalc levels</item>
		<item name="AUTOCALC_START_VALUE">starting autocalc quantity. To be used to skip some autocalc levels and start from the next ones</item>
		<item name="AVAILABLE">Available</item>
		<item name="BACK_TO_LIST">Back to the list</item>
		<item name="BACK_TO_MAIN">back to the main page</item>
		<item name="BACK_TO_TABLE">back to the table</item>
		<item name="BACK_TO_TABLES">back to tables list</item>
		<item name="BANK">Bank	</item>
		<item name="BILL">bill</item>
		<item name="BILL_ANNULLED_OK">the bill has been annulled</item>
		<item name="BILL_PRINT">bill print</item>
		<item name="BILL_RESET">bill reset</item>
		<item name="CANNOT_PREPARE_DISH">cannot be prepared</item>
		<item name="CASH">Cash</item>
		<item name="CASHIER">cashier</item>
		<item name="CATEGORIES">Categories</item>
		<item name="CATEGORIES_SHOW_ALL">Show all</item>
		<item name="CATEGORY">Category</item>
		<item name="CATEGORY_COLOR">Category color</item>
		<item name="CATEGORY_PRINT">category print</item>
		<item name="CHANGELOG">Changelog</item>
		<item name="CHARSET">iso-8859-1</item>
		<item name="CHECK_DATE">Check the date</item>
		<item name="CHECK_DAY">Check the day</item>
		<item name="CHECK_DESCRIPTION">Check the description</item>
		<item name="CHECK_HOUR">Check the hour</item>
		<item name="CHECK_MINUTE">Check the minutes</item>
		<item name="CHECK_MONTH">Check the month</item>
		<item name="CHECK_NAME">Check the name</item>
		<item name="CHECK_NAME_ALREADY_TAKEN">There is already an user with this name, please choose another</item>
		<item name="CHECK_NO_INVOICE_ERROR">Internal error: no invoice id supplied. Please contact</item>
		<item name="CHECK_NO_TYPE_ERROR">Internal error: no type supplied. Please contact</item>
		<item name="CHECK_NUMBER">Check the number.</item>
		<item name="CHECK_ORDER">Check the ordering number</item>
		<item name="CHECK_QUANTITY">check the quantity</item>
		<item name="CHECK_SURNAME">Check the surname</item>
		<item name="CHECK_TAXABLE">Check the taxable amount.</item>
		<item name="CHECK_TEMPLATE">Check the template</item>
		<item name="CHECK_TIME_BEFORE_NOW">The time can&amp;#039;t be before now</item>
		<item name="CHECK_VALUE">check the value</item>
		<item name="CHECK_YEAR">Check the year</item>
		<item name="CHEQUE_NUMBER">Check number</item>
		<item name="CITY">City</item>
		<item name="CLEARING">table clearing</item>
		<item name="CLOSE">table close</item>
		<item name="CLOSED">closed</item>
		<item name="CLOSE_TABLE">close the table</item>
		<item name="CLOSE_TABLE_ASK">Do you want to close this table?&amp;lt;br/&amp;gt;After closing it only the cashier will be able to access it.</item>
		<item name="COME_BACK_HERE">come back here</item>
		<item name="CONNECT">Connect</item>
		<item name="CONNECTED_AS">you&amp;#039;re connected as</item>
		<item name="CONTACTS">Contacts</item>
		<item name="CONTACTS_LIST">Contacts List</item>
		<item name="CONTACT_INSERT">Insert</item>
		<item name="CONTAINED">contained</item>
		<item name="CREATE_SERVICE_FEE">Insert people number</item>
		<item name="CREATION">creation</item>
		<item name="CUSTOMER">customer</item>
		<item name="CUSTOMER_DATA">customer data</item>
		<item name="DATABASE">Database</item>
		<item name="DATE">date</item>
		<item name="DEBTS">debts</item>
		<item name="DEFAULT">default</item>
		<item name="DELETE">Delete</item>
		<item name="DELETE_ALL">delete all</item>
		<item name="DELETE_ALL_CONFIRM">Are you sure you want to delete ALL THE RECORDS? This is equivalent to a total reset of this subsystem.</item>
		<item name="DELETE_DATABASE">&amp;lt;b&amp;gt;Delete the database&amp;lt;/b&amp;gt; (includes deletion of all the tables).</item>
		<item name="DELETE_DATABASE_TABLES">&amp;lt;b&amp;gt;Delete My Handy Restaurant tables&amp;lt;/b&amp;gt; from this database when deleting this record.</item>
		<item name="DELETE_NONE">No record has been deleted</item>
		<item name="DELETE_OK">Deleted successfully</item>
		<item name="DELETE_RECORD_CONFIRM">Are you sure you want to delete the following record?</item>
		<item name="DELETE_SELECTED">delete selected</item>
		<item name="DELETION">deletion</item>
		<item name="DESCRIPTION">description</item>
		<item name="DISABLED">disabled</item>
		<item name="DISCONNECTED_ERROR">Error: you\&amp;#039;ve not been disconnected.</item>
		<item name="DISCONNECTED_OK">You&amp;#039;ve been disconnected successfully.</item>
		<item name="DISCONNECTION">disconnection</item>
		<item name="DISCONNECT_ASK">Do you really want to disconnect?</item>
		<item name="DISCOUNT">Discount</item>
		<item name="DISH">Dish</item>
		<item name="DISHES">Dishes</item>
		<item name="DISHES_INGREDIENT_QUANTITIES">ingredient quantities in dishes</item>
		<item name="DISH_CODE">Code</item>
		<item name="DISH_COST">dish cost</item>
		<item name="DISH_DATA">dish data</item>
		<item name="DISH_DOES_NOT_EXIST">the dish doesn\&amp;#039;t exist</item>
		<item name="DISH_GENERIC">Generic Dish - to be used for not previewed cases, such as a very special request. Its price may be modified by the cashier.</item>
		<item name="DISH_INGREDIENT_INCLUDED">Included</item>
		<item name="DISH_INGREDIENT_NO">No</item>
		<item name="DISH_QUANTITY">dish qty</item>
		<item name="DISSOCIATE">Dissociate from table</item>
		<item name="DISSOCIATION">dissociation</item>
		<item name="EDIT">edit</item>
		<item name="EDIT_CUSTOMER_DATA">edit customer data</item>
		<item name="EDIT_NONE">No record has been edited</item>
		<item name="EDIT_OK">Updated successfully</item>
		<item name="EDIT_QUANTITIES">edit quantities</item>
		<item name="EMPTY_TABLE_BUTTON">reset the table</item>
		<item name="EMPTY_TABLE_EXPLAIN">Do you want to reset orders list?&amp;lt;h4&amp;gt;If you reset it, it will be &amp;lt;b&amp;gt;unrecoverable&amp;lt;/b&amp;gt;.&amp;lt;/h4&amp;gt;</item>
		<item name="ERROR">There has been an error</item>
		<item name="ERROR_NONE_FOUND">No record has been found</item>
		<item name="ERROR_NONE_FOUND_CATEGORY">No category has been found</item>
		<item name="ERROR_NONE_FOUND_DESTINATION">No destination has been found</item>
		<item name="ERROR_NO_CATEGORY_SELECTED">No category has been selected.</item>
		<item name="ERROR_NO_DISH_SELECTED">No dish has been selected.</item>
		<item name="ERROR_NO_INGREDIENT_SELECTED">No ingredient has been selected.</item>
		<item name="ERR_201">a generic order without price is present.&amp;lt;br&amp;gt;Before going on the price has to be set by a cashier, by clicking on the order price, then it will be possible to print the bill.</item>
		<item name="ERR_400">An error has been raised by the Operative System printing service. Please see MHR error log for further info.</item>
		<item name="ERR_405">no order has been selected</item>
		<item name="ERR_601">wrong password.&amp;lt;br/&amp;gt;Please check that you typed the correct password.&amp;lt;br/&amp;gt;Remember that the passwords are case-sensitive (Upper and lower case letters are &amp;lt;b&amp;gt;not&amp;lt;/b&amp;gt; the same), so check that your caps-lock key has not been pressed.</item>
		<item name="ERR_NO_CUSTOMER_FOUND">no customer found</item>
		<item name="ERR_UNKNOWN">Unknown error</item>
		<item name="EXCLUDING_NOT_PAID_INVOICES">excluding not paid invoices</item>
		<item name="EXTRA_CARE">extra care</item>
		<item name="EXTRA_CARE_ABBR">ATT</item>
		<item name="FAILED">failed</item>
		<item name="FAX">fax</item>
		<item name="FEW">few</item>
		<item name="FILE">File</item>
		<item name="FREE">free</item>
		<item name="FROM">from</item>
		<item name="FROM_TIME">from</item>
		<item name="GENERIC">generic</item>
		<item name="GENERIC_NOT_PRICED">generic dish not priced</item>
		<item name="GENERIC_PRICE_DESCRIPTION">This is a generic dish, so the price has to be other then 0.00.</item>
		<item name="GENERIC_PRICE_INSTRUCTION">Please, insert the new total price (for all the portions of this dish) in the following text box, then click on</item>
		<item name="GLOBAL_SEARCH">global search</item>
		<item name="GO_BACK">go back</item>
		<item name="GO_MAIN_PAGE">Go to the main page</item>
		<item name="GO_MAIN_REPORT">Go to the main report</item>
		<item name="GO_ON">Go on</item>
		<item name="HIDE_NAMES">hide the names</item>
		<item name="HIDE_ORDERS">hide the orders</item>
		<item name="HIDE_TOPLIST">hide the toplist</item>
		<item name="ID">ID</item>
		<item name="IF_YOU_ARE_NOT_DISCONNECT_0">If you\&amp;#039;re not</item>
		<item name="IF_YOU_ARE_NOT_DISCONNECT_1">&amp;lt;a href=\&amp;quot;disconnect.php\&amp;quot;&amp;gt;disconnect&amp;lt;/a&amp;gt;</item>
		<item name="INCLUDED">included</item>
		<item name="INCOME">income</item>
		<item name="INCOME_COLLAPSE">Collapse incomes</item>
		<item name="INCOME_EXPAND">Expand incomes</item>
		<item name="INCOMINGS">income</item>
		<item name="INGREDIENT">Ingredient</item>
		<item name="INGREDIENTS">Ingredients</item>
		<item name="INGREDIENT_CODE">Code</item>
		<item name="INGREDIENT_QUANTITIES">ingredients quantities</item>
		<item name="INSERT">Insert</item>
		<item name="INSERT_CUSTOMER_DATA">insert customer data</item>
		<item name="INSERT_NEW">New record</item>
		<item name="INSERT_PRIORITY">You have to insert priority.</item>
		<item name="INTERNAL_RECEIPT_ID">internal ID</item>
		<item name="INVOICE">invoice</item>
		<item name="INVOICE_ANNULLED_OK">the invoice has been annulled</item>
		<item name="ITEM">item</item>
		<item name="LANGUAGE">Language</item>
		<item name="LASTS">last</item>
		<item name="LAST_OPERATION">Last operation</item>
		<item name="LAST_UPGRADE_DONE">last successful upgrade</item>
		<item name="LIMITING_INGREDIENT">limiting ingredient</item>
		<item name="LOGIN">Login</item>
		<item name="LOGOUT">Logout</item>
		<item name="LOT">a lot</item>
		<item name="MAIN">Main</item>
		<item name="MENU">Menu</item>
		<item name="MENU_EDITING">Menu editing</item>
		<item name="MINUS">minus</item>
		<item name="MOBILE">Mobile</item>
		<item name="MODS_SETTING">mods setting</item>
		<item name="MONEY">money</item>
		<item name="MOVEMENT">movement</item>
		<item name="MOVE_TABLE">Move the table</item>
		<item name="MY_TABLES">My tables</item>
		<item name="NAME">name</item>
		<item name="NO">No</item>
		<item name="NONE">none</item>
		<item name="NOTE">note</item>
		<item name="NOT_PAID_BUTTON">Write Not Paid</item>
		<item name="NOW_SHOWING_RECORDS">records</item>
		<item name="NO_INGREDIENT_QUANTITY_INSERTED">no ingredient quantity inserted</item>
		<item name="NO_RECORD_SELECTED">No record has been selected</item>
		<item name="NO_STOCK_MOVEMENT_ASSOCIATED">no stock movement is associated to the invoice</item>
		<item name="NO_TABLE_FOUND">No table has been found</item>
		<item name="NO_UPGRADE_IS_AVAILABLE">no upgrade is available.&amp;lt;br/&amp;gt;Probably you already upgraded to the most recent database version.</item>
		<item name="NUMBER_ABBR">n</item>
		<item name="NUM_RECORDS_FOUND">records found</item>
		<item name="OBJECT">object</item>
		<item name="OBJECT_ID">object ID</item>
		<item name="OF_DAY">of</item>
		<item name="OPEN">open</item>
		<item name="OR">or</item>
		<item name="ORDER">order</item>
		<item name="ORDERS_PRINT">orders print</item>
		<item name="ORDER_PRINTED_AT">Order printed at</item>
		<item name="ORDER_PRINTED_MINS_AGO">minutes ago</item>
		<item name="ORDER_PRINTED_MINS_AGO_ABBR">mins</item>
		<item name="OUTPUT_TYPE">Output type</item>
		<item name="PAID">paid</item>
		<item name="PAID_ALREADY">The table already paid.</item>
		<item name="PAID_ASK">has the table paid?</item>
		<item name="PAID_BUTTON">write paid</item>
		<item name="PASSWORD">password</item>
		<item name="PASSWORD_CONFIRM">password check</item>
		<item name="PASSWORD_NOT_SET">the password is not set</item>
		<item name="PASSWORD_REMOVE">remove the password</item>
		<item name="PASSWORD_SET">the password is set</item>
		<item name="PAYMENT">payment</item>
		<item name="PEOPLE">people</item>
		<item name="PERCENTUAL">Percentual</item>
		<item name="PERCENT_INSERTED">percent inserted</item>
		<item name="PERIOD">period</item>
		<item name="PHONE">Phone</item>
		<item name="PIECE">piece</item>
		<item name="PLACE">place</item>
		<item name="PLUS">plus</item>
		<item name="POSSIBLE_QUANTITY">possible quantity</item>
		<item name="PRICE">Price</item>
		<item name="PRINT">Print</item>
		<item name="PRINTABLE_VERSION">printable version</item>
		<item name="PRINTER">Printer</item>
		<item name="PRINTER_TEST_PAGE">Test page</item>
		<item name="PRINTER_TEST_PAGE_END">Test page end</item>
		<item name="PRINTER_TEST_SENT">Test page sent to printers</item>
		<item name="PRINTS_ATTENTION">ATTENTION</item>
		<item name="PRINTS_BILL">bill</item>
		<item name="PRINTS_DELETED">Deleted</item>
		<item name="PRINTS_DISCOUNT">discount</item>
		<item name="PRINTS_FEW">FEW</item>
		<item name="PRINTS_GO_NOW">go now</item>
		<item name="PRINTS_GO_WITH">go with</item>
		<item name="PRINTS_INVOICE">invoice</item>
		<item name="PRINTS_LOT">A LOT</item>
		<item name="PRINTS_NUMBER_ABBR">n.</item>
		<item name="PRINTS_PEOPLE">people</item>
		<item name="PRINTS_PRIORITY">priority</item>
		<item name="PRINTS_RECEIPT">receipt</item>
		<item name="PRINTS_TABLE">table</item>
		<item name="PRINTS_TAKEAWAY">takeaway</item>
		<item name="PRINTS_TAX">tax</item>
		<item name="PRINTS_TAXABLE">taxable</item>
		<item name="PRINTS_TAX_TOTAL">total tax</item>
		<item name="PRINTS_TOTAL">total</item>
		<item name="PRINTS_WAIT">WAIT</item>
		<item name="PRINTS_WAITER">waiter</item>
		<item name="PRINT_BILL">print bill</item>
		<item name="PRINT_BILL_EXPLAIN">&amp;lt;b&amp;gt;Print bills&amp;lt;/b&amp;gt; - on if you want receipts/bill/invoices assigned to this database to be printed</item>
		<item name="PRINT_DESTINATION">Print destination</item>
		<item name="PRINT_GO_2">go with 2nd priority orders</item>
		<item name="PRINT_GO_3">go with last priority orders</item>
		<item name="PRINT_ORDERS">print orders</item>
		<item name="PRINT_SEPARATED_BILLS">print separated bills</item>
		<item name="PRIORITY">priority</item>
		<item name="PRIORITY_ABBR">p</item>
		<item name="PRIORITY_DEFAULT">suggested priority - set to none to give no suggestion</item>
		<item name="QUANTITY">quantity</item>
		<item name="QUANTITY_ABBR">q.ty</item>
		<item name="QUANTITY_TO_MODIFY">quantity to modify</item>
		<item name="QUANTITY_UPDATE">quantity update</item>
		<item name="QUEUE">queue</item>
		<item name="RECEIPT">receipt</item>
		<item name="RECEIPT_ANNULLED_OK">the receipt has been annulled</item>
		<item name="RECONNECT_WITH_PASSWORD">Reconnect with password</item>
		<item name="RECORDS">records</item>
		<item name="REMOVE">Remove</item>
		<item name="REMOVE_CUSTOMER_DATA">remove customer data</item>
		<item name="REMOVE_DEFINITIVE">Remove (definitive)</item>
		<item name="REOPEN">reopening</item>
		<item name="REOPEN_TABLE">Re-open the table</item>
		<item name="REOPEN_TABLE_ASK">Do you want to reopen this table?&amp;lt;br/&amp;gt;&amp;lt;h4&amp;gt;After reopening it anybody could acces and modify it!&amp;lt;/h4&amp;gt;</item>
		<item name="REPORTS">Reports</item>
		<item name="REPORT_GENERATE">Generate the report</item>
		<item name="RESET_SEPARATED">reset separated bills counter</item>
		<item name="RESET_SEPARATED_EXPLAIN">Are you sure to reset the separated bills counter?&amp;lt;br/&amp;gt;
If you do it &amp;lt;b&amp;gt;all&amp;lt;/b&amp;gt; the separated bills will be reprinted.&amp;lt;br/&amp;gt;
&amp;lt;br/&amp;gt;
The use of this function is suggested &amp;lt;b&amp;gt;only&amp;lt;/b&amp;gt; if you\&amp;#039;re having problems with separated orders.&amp;lt;br/&amp;gt;
&amp;lt;br/&amp;gt;
&amp;lt;br/&amp;gt;
To proceed, check the \&amp;#039;Reset separated bills\&amp;#039; checkbox and click on the \&amp;#039;OK\&amp;#039; image on the upper right corner.</item>
		<item name="SEARCH">search</item>
		<item name="SEARCH_IN">search in</item>
		<item name="SEARCH_RESULTS">search results</item>
		<item name="SEARCH_TERM_TOO_SHORT">the search term is too short. Try with a longer word.</item>
		<item name="SECONDS">seconds</item>
		<item name="SECONDS_TO_GENERATE_THE_PAGE">seconds to generate the page</item>
		<item name="SELECT_ALL">select all</item>
		<item name="SEND_TO_STOCK">send to stock</item>
		<item name="SEPARATED_BILLS">separated bills</item>
		<item name="SERVICE_FEE">service fee</item>
		<item name="SET_DEFAULT">set default</item>
		<item name="SET_TAKEAWAY_SURNAME_FIRST">you must choose the customer before printing the orders.</item>
		<item name="SHOW_NAMES">show the names</item>
		<item name="SHOW_ORDERS">show the orders</item>
		<item name="SHOW_TOPLIST">show the toplist</item>
		<item name="SOCIAL_SECURITY_NUMBER">social security number</item>
		<item name="STOCK">Stock</item>
		<item name="STOCK_INSERT_INGREDS_QUANTITIES">insert ingredient quantites</item>
		<item name="STOCK_MOVEMENT">stock movement</item>
		<item name="STOCK_MOVEMENTS">stock movements</item>
		<item name="STOCK_SITUATION">stock situation</item>
		<item name="STOCK_SYNC_ALL_DISHES">syncronize all the dishes</item>
		<item name="STOCK_SYNC_ALL_INGREDS">syncronize all the ingredients</item>
		<item name="STOCK_UPDATE_ERROR">error updating the stock data</item>
		<item name="STOCK_UPDATE_OK">stock successfully updated</item>
		<item name="STRUCTURE_ONLY">Structure only</item>
		<item name="SUBMIT">Submit</item>
		<item name="SUBSTITUTE">Substitute</item>
		<item name="SUBSTITUTE_ASK">are you sure you want to delete this order and create a new one?</item>
		<item name="SUPPLIER_FILE">supplier file</item>
		<item name="SURNAME">Surname</item>
		<item name="SUSPEND_PRINT">suspend print</item>
		<item name="SYSTEM">System</item>
		<item name="TABLE">table</item>
		<item name="TABLES">Tables</item>
		<item name="TABLE_ALREADY_IN_USE_ERROR">Table is in use by another waiter. Retry in</item>
		<item name="TABLE_HAS_BEEN_CLEARED">The table has been cleared</item>
		<item name="TABLE_NUMBER">table number</item>
		<item name="TABLE_ORDER">Ordering number of the table in the waiters&amp;#039; tables list</item>
		<item name="TABLE_TOTAL_DISCOUNTED">Table total (discounted)</item>
		<item name="TAKEAWAY">takeaway</item>
		<item name="TAKEAWAY_DATA">takeaway data</item>
		<item name="TAKEAWAY_TABLES">takeaway tables</item>
		<item name="TAXABLE">taxable</item>
		<item name="TAXES">taxes</item>
		<item name="TAX_TO_PAY">for the selected period, the taxes you should pay are</item>
		<item name="TEMPLATE">template</item>
		<item name="TESTING">testing</item>
		<item name="TEXT">Text</item>
		<item name="TIME">time</item>
		<item name="TO">to</item>
		<item name="TOPLIST">top list</item>
		<item name="TOTAL">total</item>
		<item name="TO_BE_ASSOCIATED">To assoc.</item>
		<item name="TO_TIME">to</item>
		<item name="TRANSLATION">translation</item>
		<item name="TRANSLATIONS">Translations</item>
		<item name="TRANSLATIONS_CHECKER">Tables check</item>
		<item name="TRANSLATIONS_EXPORT">Export</item>
		<item name="TYPE">type</item>
		<item name="UNITARY_VALUE">unitary value</item>
		<item name="UPDATE">Update</item>
		<item name="UPDATE_INGREDIENT_QUANTITIES">update ingredients quantities</item>
		<item name="UPDATE_NOTE">update the note</item>
		<item name="UPDATE_PRICE">Update the price</item>
		<item name="USER">user</item>
		<item name="USERS">Users</item>
		<item name="VALUE">Value</item>
		<item name="VALUE_NOW">value now</item>
		<item name="VAT_ACCOUNT">VAT account</item>
		<item name="VAT_CALCULATION">VAT calculation</item>
		<item name="VAT_RATE">Vat Rate</item>
		<item name="VAT_RATES">VAT rates</item>
		<item name="VERBOSITY">Verbosity</item>
		<item name="VERBOSITY_HIGH">High</item>
		<item name="VERBOSITY_LOW">Low</item>
		<item name="VERBOSITY_NONE">None</item>
		<item name="VISIBLE">visible</item>
		<item name="VISIBLE_TO_WAITERS">visible to waiters</item>
		<item name="VISIBLE_TO_WAITERS_HELP">Allows to hide the item in the waiters\&amp;#039; section. You can disable this function in the configuration file to make all the items visible.</item>
		<item name="WAITER">waiter</item>
		<item name="WAITERS">Waiters</item>
		<item name="WHO">who</item>
		<item name="WHO_ARE_YOU">who are you?</item>
		<item name="XML">XML</item>
		<item name="MSG_WAITER_NOT_CONNECTED_ERROR">You are not connected!</item>
		<item name="YES">Yes</item>
		<item name="ZIP_CODE">Zip code</item>
		<item name="NO_PASSWORD_GIVEN">No password given for the following account!!</item>
		<item name="SELECT_USER">Select a user to login</item>
		<item name="GIVE_PASSWORD">Please write a password to login</item>
		<item name="TOTAL_WAITER_INCOME">Total income for</item>
		<item name="INCOME">Income</item>
		<item name="INFORMATION">Information</item>
	</data>
</SmartRestaurant>